### PR TITLE
Add elm (0.16.0) implementation

### PR DESCRIPTION
**Pull request by toburger**
Hi Tylor,

I've created an elm (elm-http) implementation.
It's not a single JavaScript library but a whole new language ecosystem.
So I let you to decide if you want add it to the table...

* Bear in mind, that it is a compile step involved to generate the JavaScript. The compiled script files are committed with the sources, so the code runs OOTB.
* The Optimized version differs from the Naive implementation by the introduction of the lazy function applied in two (!) places. So I don't know if it is worth speaking of a naive and optimized version. It's more of a mechanical step adding laziness to the code, so I would speak more of an "idiomatic" version then an "optimized" version (the "naive" version could then be deleted).

Best regards
Tobias

### CODE REVIEW

**Comment by TylorS** [comment]
Hello @toburger I would generally suggest making this PR to the original repo
https://github.com/mathieuancelin/js-repaint-perfs

That said, I will accept this and PR all of my changes back to that the original repo if you would prefer. I plan to at least try to merge my work back into the original repository.

**Comment by toburger** [comment]
Yeah no problem! I came to your repo because it was mentioned on twitter and so I found yours to be more recent.

**Comment by TylorS** [comment]
So would you like for me to merge this?

**Comment by toburger** [comment]
Yes, plaese. It's less work for me at least.. :)

**Comment by TylorS** [comment]
:+1: 
Merged

**Comment by toburger** [comment]
thx! :+1:

**Comment by toburger** [comment]
Hi @TylorS,
are you planning to make a pull request to Mathieu Ancelin's repo in the near future?
If not I will make my own pull request. Sorry for my confusion by pulling to your repo. My bad.

**Comment by TylorS** [comment]
Yeah, I keep meaning to but always end up forgetting, I'll put it on my list of todos and try to get this done soon, but of course, feel free to PR directly because I'm a bit of a bum

**Pull request merged**
